language: node_js
node_js:
- "stable"
cache: yarn
# we skip install to use parallelized build stage
install: skip
jobs:
  include:
    - stage: install app
      script: pwd && ls && cd veto-backend && yarn
